version: '3.8'

services:
  features:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: features
    command: python3 -m lib.applications.features
    environment:
      RABBIT_MQ_DSN: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
     - ihddocker

  model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model
    command: python3 -m lib.applications.model
    environment:
      RABBIT_MQ_DSN: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - features
      - rabbitmq
    networks:
     - ihddocker

  metric:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metric
    links:
      - rabbitmq
    command: python3 -m lib.applications.metric
    environment:
      RABBIT_MQ_DSN: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - model
      - rabbitmq
    networks:
     - ihddocker

  plot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plot
    command: python3 -m lib.applications.plot

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ihddocker

networks:
  ihddocker:

volumes:
  rabbitmq-data:
